### ISSUE TITLE
Fork on Github button does not open Github

### ISSUE THREAD

**Issue by John-Ingram** [tjcouch1/transferable-discipleship#11]
The "Fork the template on Github"  button does not exit the app on Android 14 (Pixel 7 pro).

Very minor issue obviously.

**Comment by tjcouch1** [comment]
Released in [0.1.1-update-2](https://github.com/tjcouch1/transferable-discipleship/releases/tag/v0.1.1-update-2)
Edit: not fixed :(

**Comment by tjcouch1** [comment]
Seems to be actually fixed in release [v0.1.1-update-3](https://github.com/tjcouch1/transferable-discipleship/releases/tag/v0.1.1-update-3)
